# Generated by Django 4.1.7 on 2023-04-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='rider',
        ),
    ]
