# Generated by Django 4.1.7 on 2023-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recepient', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
