# Generated by Django 4.1.7 on 2023-04-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'OrderDetails'},
        ),
    ]
