# Generated by Django 4.1.7 on 2023-04-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
        ('orders', '0004_alter_orderdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='rider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='riders.rider'),
        ),
    ]
