# Generated by Django 4.1.7 on 2023-04-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='voided_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
