# Generated by Django 4.1.7 on 2023-04-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_voided_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='voided',
        ),
        migrations.RemoveField(
            model_name='product',
            name='voided_date',
        ),
    ]
